install.packages('MASS')
install.packages('LaplacesDemon')
install.packages('cluster')
install.packages('fpc')


CRP=function(alpha,N){
  #########
  #Function to carry out the CRP.
  #Inputs: Concentration parameter alpha and N, the number of customers
  #Output: A vector of length N that contains the cluster assignemnt of each customer
  ########
  
  cluster_assignments=rep(0,N)
  
  #the first person picks table 1 with probability of 1
  cluster_assignments[1]=1 
  
  #iterate through all of the remaining customers 
  for (i in 2:N){
    
    # calculate the probability that a person chooses a new table
    probs=rep(0,max(cluster_assignments)+1)
    probs[max(cluster_assignments)+1]=(alpha/(i-1+alpha)) 
    
    #probability of picking each of the occupied tables
    for (k in 1:max(cluster_assignments)){
      probs[k]=sum(cluster_assignments==k)/(i-1+alpha)
      
    }
    
    #choosing a table based on probabilites 
    x=seq(1,max(cluster_assignments)+1,1) 
    choice=sample(x,size=1,FALSE,probs)
    
    #update the cluster assignment list with the chosen cluster
    cluster_assignments[i]=choice
  }
  #return list of cluster assignment for each customer
  return(cluster_assignments)
}


### Note that my function is for two dimensional data points. Can be generalized.
DPGMM= function(num_datapoints,alpha, mu_0,kappa_0,psi_0,nu_0){
  #######
  # Function to Carry out the DPGMM
  # Inputs: number of data points, alpha and hyperparameters for NIW
  # Output: Data points generated by the DPGMM
  ######
  
  #compute the cluster assignments using the CRP
  # Use the CRP function defined above
  cluster_assignments=CRP(alpha,num_datapoints)
  number_of_clusters=max(cluster_assignments)

  #initialize lists to store the sigma and mu values for each cluster
  sigma_list=matrix(0,number_of_clusters,4)
  mu_list=matrix(0,number_of_clusters,2)
  
  #for each cluster, draw a sgima and mu from the NIW and store in the list
  for (i in 1:number_of_clusters){
    #draw sigma using hyper parameters 
    sigma_draw=LaplacesDemon::rinvwishart(nu_0,psi_0)
    sigma_list[i,]=as.vector(sigma_draw)
    
    #draw mu using hyperparameters and the sigma drawn above
    mu_draw=MASS::mvrnorm(n = 1, mu_0, (1/kappa_0)*sigma_draw)
    mu_list[i,]=as.vector(mu_draw)

  }
 
  #initialize lists to store the data points
  x_1=rep(0,num_datapoints)
  x_2=rep(0,num_datapoints)
  
  #generate each datapoint
  for (j in 1:num_datapoints){
    
    #find the cluster that the CRP assigned that point 
    j_cluster=cluster_assignments[j]
    
    #find the sigma and mu of that cluster
    j_sigma=matrix(sigma_list[j_cluster,],2,2)
    j_mu=matrix(mu_list[j_cluster,],1,2)
    
    #draw a point from that normal distribution
    new_point=MASS::mvrnorm(n = 1, j_mu, j_sigma)
    
    #store the new point in the lists 
    x_1[j]=new_point[1]
    x_2[j]=new_point[2]
    
    
  }
  return(list(v1=x_1,v2=x_2,v3=cluster_assignments))
}  

###### Use the function I just made to create various datasets ########

#### Base Value Hyper Parameters
mu_0=matrix(1,1,2)
kappa_0=1
psi_0=matrix(c(1,0,0,1),2,2)
nu_0=2

hi=DPGMM(100,1,mu_0,kappa_0,psi_0,nu_0)
data=cbind(hi$v1,hi$v2)  
plot(hi$v1,hi$v2,xlab="Component 1", ylab="Component 2")
cluster::clusplot(data,hi$v3, color=TRUE, shade=TRUE)

#### Vary alpah: 0.1 and 10
hi=DPGMM(100,0.1,mu_0,kappa_0,psi_0,nu_0)
data=cbind(hi$v1,hi$v2)  
plot(hi$v1,hi$v2,xlab="Component 1", ylab="Component 2")
cluster::clusplot(data,hi$v3, color=TRUE, shade=TRUE)

hi=DPGMM(100,10,mu_0,kappa_0,psi_0,nu_0)
data=cbind(hi$v1,hi$v2)  
plot(hi$v1,hi$v2,xlab="Component 1", ylab="Component 2")
cluster::clusplot(data,hi$v3, color=TRUE, shade=TRUE)
#31 clusters

#### Vary m_0
mu_0=matrix(5,1,2)
kappa_0=1
psi_0=matrix(c(1,0,0,1),2,2)
nu_0=2

hi=DPGMM(100,1,mu_0,kappa_0,psi_0,nu_0)
data=cbind(hi$v1,hi$v2)  
plot(hi$v1,hi$v2,xlab="Component 1", ylab="Component 2")
cluster::clusplot(data,hi$v3, color=TRUE, shade=TRUE)

mu_0=matrix(.1,1,2)
hi=DPGMM(100,1,mu_0,kappa_0,psi_0,nu_0)
data=cbind(hi$v1,hi$v2)  
plot(hi$v1,hi$v2,xlab="Component 1", ylab="Component 2")
cluster::clusplot(data,hi$v3, color=TRUE, shade=TRUE)

#### Vary kappa_0
mu_0=matrix(1,1,2)
kappa_0=.1
psi_0=matrix(c(1,0,0,1),2,2)
nu_0=2

hi=DPGMM(100,1,mu_0,kappa_0,psi_0,nu_0)
data=cbind(hi$v1,hi$v2)  
plot(hi$v1,hi$v2,xlab="Component 1", ylab="Component 2")
cluster::clusplot(data,hi$v3, color=TRUE, shade=TRUE)

kappa_0=10
hi=DPGMM(100,1,mu_0,kappa_0,psi_0,nu_0)
data=cbind(hi$v1,hi$v2)  
plot(hi$v1,hi$v2,xlab="Component 1", ylab="Component 2")
cluster::clusplot(data,hi$v3, color=TRUE, shade=TRUE)

#### Vary Psi_0
mu_0=matrix(1,1,2)
kappa_0=1
psi_0=matrix(c(.1,0,0,.1),2,2)
nu_0=2

hi=DPGMM(100,1,mu_0,kappa_0,psi_0,nu_0)
data=cbind(hi$v1,hi$v2)  
plot(hi$v1,hi$v2,xlab="Component 1", ylab="Component 2")
cluster::clusplot(data,hi$v3, color=TRUE, shade=TRUE)

psi_0=matrix(c(10,0,0,10),2,2)
hi=DPGMM(100,1,mu_0,kappa_0,psi_0,nu_0)
data=cbind(hi$v1,hi$v2)  
plot(hi$v1,hi$v2,xlab="Component 1", ylab="Component 2")
cluster::clusplot(data,hi$v3, color=TRUE, shade=TRUE)

### Vary nu
mu_0=matrix(1,1,2)
kappa_0=1
psi_0=matrix(c(1,0,0,1),2,2)
nu_0=5

hi=DPGMM(100,1,mu_0,kappa_0,psi_0,nu_0)
data=cbind(hi$v1,hi$v2)  
plot(hi$v1,hi$v2,xlab="Component 1", ylab="Component 2")
cluster::clusplot(data,hi$v3, color=TRUE, shade=TRUE)


nu_0=20

hi=DPGMM(100,1,mu_0,kappa_0,psi_0,nu_0)
data=cbind(hi$v1,hi$v2)  
plot(hi$v1,hi$v2,xlab="Component 1", ylab="Component 2")
cluster::clusplot(data,hi$v3, color=TRUE, shade=TRUE)





